use_frameworks!

platform :ios, '8.0'

target 'KULimitLengthTextField_Example' do
  pod 'KULimitLengthTextField', :path => '../'

  target 'KULimitLengthTextField_Tests' do
    inherit! :search_paths

    
  end
end
